# pytest.ini
[pytest]
norecursedirs = .* .venv temp src site-packages
addopts = -vv -s --cov=src --cov-report=term-missing --cov-report=html  --cov-config=.coveragerc --durations=10
pythonpath = "src"
timeout = 120
filterwarnings =
    ignore::DeprecationWarning:pydantic.*
    ignore::DeprecationWarning:pkg_resources.*
    ignore::DeprecationWarning:google.rpc.*
    ignore::DeprecationWarning:google._upb.*
    ignore::DeprecationWarning:google.protobuf.*